animeasy/urls.py
"""
URL patterns for animeasy
"""

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('newsletter/', include('newsletter.urls')),
    path('contact/', include('contact.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bag/urls.py
"""
URL patterns for the bag app
"""
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

contact/urls.py
"""
URLS for the contact app
"""
from django.urls import path
from . import views

urlpatterns = [
    path('', views.contact, name='contact'),
    path('success/<int:ticket_id>/', views.contact_success, name='contact_success'),
    path('tickets/', views.contact_tickets, name='contact_tickets'),
    path('tickets/<int:ticket_id>/', views.ticket_detail, name='ticket_detail'),
    path('privacy/', views.privacy_policy, name='privacy_policy'),
    path('terms-and-conditions/', views.terms_and_conditions, name='terms_and_conditions'),
]

contact/models.py
"""
Creates models for tickets and their replies
"""
from django.db import models
from profiles.models import UserProfile
status = models.CharField(max_length=10, choices=[('pending', 'Pending'), ('resolved', 'Resolved')])

class Ticket(models.Model):
    """
    Model for ticket (send email to admin)
    """
    email = models.EmailField(null=True, max_length=254)
    date_received = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=100)
    content = models.TextField(null=True)
    status = models.CharField(max_length=10, choices=[
            ('pending', 'Pending'),
            ('resolved', 'Resolved')
        ],
        default='pending'
    )

    def __str__(self):
        return self.title

class TicketReply(models.Model):
    """
    Model for reply (from admin to user)
    """
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    admin = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    reply = models.TextField(null=True)
    date_reply = models.DateTimeField(auto_now_add=True)

    class Meta:
        get_latest_by = 'date_reply'

    def __str__(self):
        return f'Reply to: {self.ticket.title}'

contact/forms.py
"""
Sets up the forms for the contact app
"""
from django import forms
from .models import Ticket, TicketReply

class TicketForm(forms.ModelForm):
    """
    Creates contact form ticket
    """
    class Meta:
        model = Ticket
        fields = ['title', 'content', 'email', ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({
            'placeholder': 'Subject',
            'autocomplete': 'off',
            'class' : 'form-control my-1',
        })
        self.fields['email'].label = False
        self.fields['email'].widget.attrs.update({
            'placeholder': 'Email Address',
            'autocomplete': 'off',
            'class' : 'form-control my-1',
        })
        self.fields['title'].label = False
        self.fields['content'].widget.attrs.update({
            'placeholder': 'What can we help you with?',
            'autocomplete': 'off',
            'class' : 'form-control my-1',
        })
        self.fields['content'].label = False

class TicketReplyForm(forms.ModelForm):
    """
    Creates replies and attaches them to ticket
    """
    class Meta:
        model = TicketReply
        fields = [ 'reply',]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['reply'].widget.attrs.update({
            'placeholder': 'Reply',
            'autocomplete': 'off',
            'class' : 'form-control m',
        })
        self.fields['reply'].label = False

contact/views.py
"""
Handles the views for the contact app (complaint form, ticket list and replies)
"""
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.template.loader import render_to_string
from profiles.models import UserProfile
from .models import Ticket, TicketReply
from .forms import TicketForm, TicketReplyForm


def contact(request):
    """
    User can submit a ticket
    """
    form = TicketForm()
    template = 'contact/contact_form.html'
    email = Ticket.email

    # Allows a user to create a ticket
    if request.method == 'POST':
        form = TicketForm(request.POST)
        if form.is_valid():
            ticket = form.save()
            title = form.cleaned_data.get('title')
            email = form.cleaned_data.get('email')
            content = form.cleaned_data.get('content')
            subject = render_to_string(
                'contact/contact_emails/contact_email_subject.txt', 
                {'title': title}
            )
            body = render_to_string(
                'contact/contact_emails/contact_email_body.txt', 
                {'content': content, 'email': email,}
            )

            send_mail(
                subject,
                body,
                'contact@animeasy.com',
                [email],
                fail_silently=False,
            )
            messages.success(request, 'Your ticket has been submitted')
            return redirect('contact_success', ticket_id=ticket.id)

        form = TicketForm()

    context = {
        'form': form,
    }
    return render(request, template, context)


def contact_success(request, ticket_id):
    """
    Users are redirected here when a ticket is sent
    """
    ticket = get_object_or_404(Ticket, pk=ticket_id)

    #"""
    #Could attach tickets to account later
    #if request.user.is_authenticated:
    #    profile = UserProfile.objects.get(user=request.user)
    #    #Attach user to order
    #    order.user_profile = profile
    #    order.save()
    #"""
    context = {
        'ticket': ticket,
    }
    return render(request, "contact/contact_success.html", context)

@login_required
def contact_tickets(request):
    """
    A view to show all tickets
    """
    if request.user.is_superuser:
        tickets = Ticket.objects.all().order_by('-date_received')

        # Filter by unresolved status
        unresolved = request.GET.get('unresolved')
        if unresolved == 'true':
            tickets = tickets.filter(status='pending')

        # Filter by unresolved status
        resolved = request.GET.get('resolved')
        if resolved == 'true':
            tickets = tickets.filter(status='resolved')

        # Sorting by date ascending and descending
        sort_by_date = request.GET.get('sort')
        if sort_by_date == 'asc':
            tickets = tickets.order_by('date_received')
        elif sort_by_date == 'desc':
            tickets = tickets.order_by('-date_received')

        # Sorting by ID number
        sort_by_id = request.GET.get('sort_by_id')
        if sort_by_id == 'asc':
            tickets = tickets.order_by('id')
        elif sort_by_id == 'desc':
            tickets = tickets.order_by('-id')

        admin = TicketReply.objects.all()
        context = {
            'tickets': tickets,
            'admin': admin,
        }

        return render(request, 'contact/contact_tickets.html', context)
    messages.error(request, 'You do not have permission to view this page')
    return redirect('home')

def ticket_detail(request, ticket_id):
    """ Returns page with all ticket information """
    ticket = get_object_or_404(Ticket, pk=ticket_id)
    # Allows admin to reply to a ticket
    template = 'contact/ticket_detail.html'
    email = ticket.email
    reply = None
    if request.user.is_superuser:
        if request.method == 'POST':
            form = TicketReplyForm(request.POST)
            if form.is_valid():
                reply = TicketReply()
                reply.ticket = ticket
                reply.reply = form.cleaned_data.get('reply')
                email_body = reply.reply
                reply.admin = UserProfile.objects.get(user=request.user)
                reply.save()
                title = ticket.title
                send_mail(
                    title,
                    email_body,
                    'support@animeasy.com',
                    [email],
                    fail_silently=False,
                )
                messages.success(request, 'Reply was sent to ' + email )
                ticket.status = 'resolved'
                ticket.save()
                return redirect('contact_tickets')
        else:
            form = TicketReplyForm()
        return render(request, template, {'form': form, 'ticket': ticket})
    messages.error(request, 'You do not have permission to reply to tickets')
    return redirect('home')

def privacy_policy(request):
    """
    Shows the privacy policy page
    """
    template = 'contact/privacy_policy.html'
    return render(request, template)

def terms_and_conditions(request):
    """
    Shows the terms and conditions page
    """
    template = 'contact/terms_and_conditions.html'
    return render(request, template)

contact/templates/contact/contact_form.html
{% extends 'base.html' %}
{% block page_header %}
Contact Us
{% endblock %}
{% block content %}
<div class="container">
    <div>
        <p>For any queries, make sure to check out our <a href="{% url 'install_guide' %}">installation guide</a> or our <a href="{% url 'faq' %}">FAQ section.</a></p>
        <br>
        <p>Alternatively, feel free to get in touch using the form below.</p>

    </div>
    <div class="card p-3 mt-4">
        <form method="POST" action="{% url 'contact' %}">
            {% csrf_token %}
            
            {{ form | crispy }}
            
            <button type="submit" class="btn btn-danger btn-lg float-end mt-5">Send</button>
        </form>
    </div>
</div>
{% endblock %}

contact/templates/contact/contact_success.html
{% extends 'base.html' %}

{% block page_header %}
Thanks for getting in touch!
{% endblock %}

{% block content %}
<div class="container">
    <div class="h3 my-5">
        <p>
            Your ticket has been received. A member of our time will be in touch shortly at <i>{{ ticket.email }}</i>.
        </p>
    </div>
    <div class="card" style="min-height: 40vh;">
        <div class="card-header h6 mb-3">
            Subject: {{ ticket.title }}
        </div> 
        <div class="card-body p-4">
            <div class="mb-5"><strong>You wrote:</strong>
            <p>{{ ticket.content }}</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

contact/templates/contact/contact_tickets.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="dropdown float-end mb-4">
        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Filter Tickets
        </a>
        <ul class="dropdown-menu">
            <li>
                <a class="dropdown-item" href="?unresolved=true">Unresolved</a>
            </li>
            <li>
                <a class="dropdown-item" href="?resolved=true">Resolved</a>
            </li>
            <li>
                <a class="dropdown-item" href="?sort=asc">Sort by date (ascending)</a>
            </li>
            <li>
                <a class="dropdown-item" href="?sort=desc">Sort by date (descending)</a>
            </li>
            <li>
                <a class="dropdown-item" href="?sort_by_id=asc">Sort by ID (ascending)</a>
            </li>
            <li>
                <a class="dropdown-item" href="?sort_by_id=desc">Sort by ID (descending)</a>            
            </li>
            <li>
                <a class="dropdown-item" href="{% url 'contact_tickets' %}">Clear All Filters</a>            
            </li>
        </ul>
    </div>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Issue</th>
            <th scope="col">Email</th>
            <th scope="col">Date</th>
            <th scope="col">Status</th>
            <th scope="col">Resolved by</th>
            <th scope="col">Date resolved</th>
        </tr>
        </thead>
        <tbody>
            {% for ticket in tickets %}
            <tr>
                <td>
                    <a href="{% url 'ticket_detail' ticket.id %}">
                    {{ ticket.id }} 
                    </a>
                </td>
                <td>
                    <a href="{% url 'ticket_detail' ticket.id %}">
                        {{ ticket.title|truncatechars_html:30 }}
                    </a>
                </td>
                <td>
                    {{ ticket.email}}
                </td>
                <td>
                    {{ ticket.date_received }}
                </td>
                <td>
                    {% if ticket.status == "pending" %}
                    <span class="badge text-bg-warning">
                        {{ ticket.status }}
                    </span>
                    {% elif ticket.status == "resolved" %}
                    <span class="badge text-bg-success">
                        {{ ticket.status }}
                    </span>
                    {% else %}
                    <span class="badge text-bg-secondary">
                        {{ ticket.status }}
                    </span>
                    {% endif %}
                </td>
                <td>
                    {% with latest_reply=ticket.ticketreply_set.latest %}
                        {% if latest_reply %}
                            {{ latest_reply.admin }}
                        {% else %}
                            ----
                        {% endif %}
                    {% endwith %}
                </td>
                <td>
                    {% with latest_reply=ticket.ticketreply_set.latest %}
                        {% if latest_reply %}
                            {{ latest_reply.date_reply }}
                        {% else %}
                            ----
                        {% endif %}
                    {% endwith %}
                </td>
            </tr>
        {% endfor%}
        </tbody>
    </table>
</div>
{% endblock %}

contact/templates/contact/terms_and_conditions.html
{% extends 'base.html' %}

{% block page_header %}
Terms and Conditions 
{% endblock %}

{% block content %}
<div class="container m-5">
<p>Last updated: May 08, 2024</p>


    <p>These Terms of Service ("Terms") govern your use of Animeasy Tools (the "Service"), provided by Animeasy ("we," "us," or "our"). 
        By accessing or using the Service, you agree to be bound by these Terms. 
        If you do not agree to these Terms, you may not use the Service.</p>

    <h2>1. Description of Service</h2>
    <p>The Service provided by Animeasy allows users to purchase digital downloads of products. Upon purchase, users are granted 
        the right to distribute the purchased digital download to others.</p>

    <h2>2. User Conduct</h2>
    <p>By using the Service, you agree not to:</p>
    <ul>
        <li>Violate any applicable laws, regulations, or third-party rights.</li>
        <li>Use the Service for any unlawful or fraudulent purpose.</li>
        <li>Attempt to interfere with, disrupt, or disable any part of the Service.</li>
    </ul>

    <h2>3. Purchases</h2>
    <p>When you make a purchase through the Service, you agree to provide accurate and complete information. You also agree to pay 
        all charges incurred in connection with your purchase.</p>

    <h2>4. Digital Downloads</h2>
    <p>Upon purchase, users are granted a non-exclusive, worldwide, royalty-free license to distribute the purchased digital download to others.
         This license is non-transferable and revocable.</p>

    <h2>5. Intellectual Property</h2>
    <p>All content included on the Service, such as text, graphics, logos, images, audio clips, digital downloads, and data compilations, 
        is the property of Animeasy or its content suppliers and protected by copyright laws.</p>

    <h2>6. Limitation of Liability</h2>
    <p>In no event shall Animeasy be liable for any indirect, incidental, special, consequential, or punitive damages,
         including but not limited to lost profits, arising out of or related to your use of the Service.</p>

    <h2>7. Changes to Terms</h2>
    <p>We reserve the right to modify these Terms at any time. Any changes will be effective immediately upon posting. Your continued use
         of the Service after the posting of changes constitutes your acceptance of such changes.</p>

    <h2>8. Governing Law</h2>
    <p>These Terms shall be governed by and construed in accordance with the laws of EU, without regard to its conflict of law provisions.</p>

    <h2>9. Contact Us</h2>
    <p>If you have any questions about these Terms, please contact us <a href="{% url 'contact' %}">here.</a></p>

</div>
{% endblock %}

contact/templates/contact/ticket_detail.html
{% extends 'base.html' %}

{% block page_header %}
Support Ticket #{{ ticket.id}}
{% endblock%}



{% block content %}
<div class="container"> 
    <div class="card">
        <div class="card-header">
            <div class="card-title">
                <strong>From:</strong> {{ ticket.email}}
            </div>
            <div class="card-title">
                <strong>Date:</strong> {{ ticket.date_received }}
            </div>
            <div class="card-title">
                <strong>Subject:</strong> {{ ticket.title }}
            </div>
        </div>
    </div>
    <div class="card-body">
        <p>
            {{ ticket.content }}
        </p>
    </div> 

    {% for reply in ticket.ticketreply_set.all %}
    <div class="card my-4">
        <div class="card-header">
            <div class="card-title">
                <strong>Admin:</strong> {{ reply.admin }}
            </div>
            <div class="card-title">
                <strong>Date:</strong> {{ reply.date_reply }}
            </div>
        </div>
        <div class="card-body">
            <p>
                {{ reply.reply }}
            </p>
        </div>
    </div> 
    {% endfor %}

    <div class="card p-3">
        <form method="POST" action="{% url 'ticket_detail' ticket.id %}">
            <div class="h5">
                Replying to: {{ ticket.title|truncatechars_html:30 }}
            </div>
            {% csrf_token %}

            {{ form | crispy }}
             <button type="submit" class="btn btn-danger mt-5">Reply Ticket</button>
        </form>
    </div>
</div>
{% endblock %}